"""initial schema

Revision ID: 76dcf364c4e7
Revises: 
Create Date: 2026-01-01 23:58:05.023053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '76dcf364c4e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("id LIKE 'res_%'", name='restaurant_id_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PEN', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(status = 'paid' AND paid_at IS NOT NULL) OR (status != 'paid' AND paid_at IS NULL)", name='paid_at_consistency'),
    sa.CheckConstraint("status IN ('created', 'processing', 'paid', 'failed')", name='valid_payout_status'),
    sa.CheckConstraint('amount_cents > 0', name='positive_payout_amount'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payouts_pending', 'payouts', ['restaurant_id', 'status'], unique=False, postgresql_where="status IN ('created', 'processing')")
    op.create_table('processor_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restaurant_id', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PEN', nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('fee_cents', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("event_type IN ('charge_succeeded', 'refund_succeeded', 'payout_paid')", name='valid_event_type'),
    sa.CheckConstraint('amount_cents >= 0', name='positive_amount'),
    sa.CheckConstraint('fee_cents >= 0', name='positive_fee'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_processor_events_event_id', 'processor_events', ['event_id'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PEN', nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_event_id', sa.String(length=100), nullable=True),
    sa.Column('related_payout_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("entry_type IN ('sale', 'commission', 'refund', 'payout_reserve')", name='valid_entry_type'),
    sa.ForeignKeyConstraint(['related_event_id'], ['processor_events.event_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_payout_id'], ['payouts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_available_at', 'ledger_entries', ['available_at'], unique=False, postgresql_where='available_at IS NOT NULL')
    op.create_index('idx_ledger_restaurant_currency', 'ledger_entries', ['restaurant_id', 'currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ledger_restaurant_currency', table_name='ledger_entries')
    op.drop_index('idx_ledger_available_at', table_name='ledger_entries', postgresql_where='available_at IS NOT NULL')
    op.drop_table('ledger_entries')
    op.drop_index('idx_processor_events_event_id', table_name='processor_events')
    op.drop_table('processor_events')
    op.drop_index('idx_payouts_pending', table_name='payouts', postgresql_where="status IN ('created', 'processing')")
    op.drop_table('payouts')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
